# -*- coding: utf-8 -*-
"""protein_backbone.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17owOm5kSl0_1_YIja2UH_9h9B2hRQg5t

## **Import libraries, data and Preprocessing**
"""

import pandas as pd
from sklearn.preprocessing import OneHotEncoder, LabelEncoder, MinMaxScaler
from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow.keras import layers, Model

data = pd.read_csv('combined_data.csv')

data.head()

data.shape

data.info()

data.isnull().sum()

data.describe()

numeric_cols = data.select_dtypes(include=['float64', 'int64']).columns
print("Numeric columns (float + int):")
print(numeric_cols)
numeric_data = data[numeric_cols]
numeric_data = numeric_data.fillna(numeric_data.mean())

data = data.fillna(data.mode().iloc[0])
data.isnull().sum()

# ----- Encode ss -----
ohe_ss = OneHotEncoder(handle_unknown="ignore", sparse_output=False)
ss_arr = ohe_ss.fit_transform(data[["ss"]].astype(str))
ss_cols = ohe_ss.get_feature_names_out(["ss"])
df_ss = pd.DataFrame(ss_arr, columns=ss_cols, index=data.index)

# ----- Encode aa -----
ohe_aa = OneHotEncoder(handle_unknown="ignore", sparse_output=False)
aa_arr = ohe_aa.fit_transform(data[["aa"]].astype(str))
aa_cols = ohe_aa.get_feature_names_out(["aa"])
df_aa = pd.DataFrame(aa_arr, columns=aa_cols, index=data.index)

# ----- Build final dataframe -----
df = pd.concat([data.drop(columns=["ss", "aa"]), df_ss, df_aa], axis=1)

# -----------------------------
# 1. One-hot encode chain_id
# -----------------------------
ohe_chain = OneHotEncoder(handle_unknown="ignore", sparse_output=False)
chain_arr = ohe_chain.fit_transform(df[["chain_id"]].astype(str))
chain_cols = ohe_chain.get_feature_names_out(["chain_id"])
df_chain = pd.DataFrame(chain_arr, columns=chain_cols, index=df.index)

# -----------------------------
# 2. Label-encode PDB column
# -----------------------------
le_pdb = LabelEncoder()
pdb_numeric = le_pdb.fit_transform(df["PDB"].astype(str))
df_pdb = pd.DataFrame({"PDB_numeric": pdb_numeric}, index=df.index)

# -----------------------------
# 3. Build final dataframe
# -----------------------------
df = pd.concat(
    [
        df.drop(columns=["chain_id", "PDB"]),
        df_chain,
        df_pdb
    ],
    axis=1
)

df.head()

target_columns = ["CAx", "CAy", "CAz", "Nx", "Ny", "Nz", "Cx", "Cy", "Cz", "Ox", "Oy", "Oz"]
y = df[target_columns]
X = df.drop(columns=target_columns)

def Preprocessing(X, Y, test_size=0.30, seed=0, shuffle=False):
    # Convert to float
    X = X.astype(float)
    Y = Y.astype(float)

    # -------------------------
    # Normalize X
    # -------------------------
    x_scaler = MinMaxScaler(feature_range=(-1, 1))
    X_norm = x_scaler.fit_transform(X)

    # -------------------------
    # Normalize Y
    # -------------------------
    y_scaler = MinMaxScaler(feature_range=(-1, 1))
    Y_norm = y_scaler.fit_transform(Y)

    # -------------------------
    # Train/Test split ONLY
    # -------------------------
    x_train, x_test, y_train, y_test = train_test_split(
        X_norm, Y_norm,
        test_size=test_size,
        shuffle=shuffle,
        random_state=seed
    )

    # Shapes
    print("x_train shape:", x_train.shape)
    print("y_train shape:", y_train.shape)
    print("x_test shape:", x_test.shape)
    print("y_test shape:", y_test.shape)

    return x_train, x_test, y_train, y_test, x_scaler, y_scaler

x_train, x_test, y_train, y_test, x_scaler, y_scaler = \
    Preprocessing(X, y, test_size=0.30, seed=0, shuffle=False)

"""## **Model (CNN Attention)**"""

import tensorflow as tf

def kabsch_align(pred, true):
    """
    pred, true: (batch, N, 3)
    Returns: aligned_pred (batch, N, 3)
    """
    pred_mean = tf.reduce_mean(pred, axis=1, keepdims=True)
    true_mean = tf.reduce_mean(true, axis=1, keepdims=True)

    pred_centered = pred - pred_mean
    true_centered = true - true_mean

    # Covariance: (B, 3, 3)
    cov = tf.matmul(pred_centered, true_centered, transpose_a=True)

    # SVD
    s, u, v = tf.linalg.svd(cov)  # u: (B,3,3), v: (B,3,3)

    # R0 = V * U^T
    u_t = tf.transpose(u, perm=[0, 2, 1])
    r0 = tf.matmul(v, u_t)  # (B,3,3)

    # ---- manual 3x3 determinant of r0 (XLA-safe) ----
    a = r0[:, 0, 0]
    b = r0[:, 0, 1]
    c = r0[:, 0, 2]
    d = r0[:, 1, 0]
    e = r0[:, 1, 1]
    f = r0[:, 1, 2]
    g = r0[:, 2, 0]
    h = r0[:, 2, 1]
    i = r0[:, 2, 2]

    det_r0 = (
        a * (e * i - f * h)
        - b * (d * i - f * g)
        + c * (d * h - e * g)
    )  # (B,)

    sign = tf.sign(det_r0)  # (B,)

    # D = diag(1, 1, sign)
    ones = tf.ones_like(sign)
    diag = tf.stack([ones, ones, sign], axis=-1)  # (B,3)
    dmat = tf.linalg.diag(diag)  # (B,3,3)

    # Proper rotation: R = V * D * U^T
    r = tf.matmul(v, tf.matmul(dmat, u_t))  # (B,3,3)

    aligned = tf.matmul(pred_centered, r) + true_mean  # (B,N,3)
    return aligned

def kabsch_crmsd(y_true, y_pred):
    batch = tf.shape(y_pred)[0]
    y_pred = tf.reshape(y_pred, (batch, -1, 3))
    y_true = tf.reshape(y_true, (batch, -1, 3))

    aligned = kabsch_align(y_pred, y_true)
    diff = aligned - y_true

    crmsd = tf.sqrt(tf.reduce_mean(tf.reduce_sum(tf.square(diff), axis=-1)))/1.5
    return crmsd

import tensorflow as tf
from tensorflow.keras import layers, Model
import keras

# -------------------------
# Custom Metrics
# -------------------------
# -----------------------------------------
# RMSD
# -----------------------------------------
def rmsd_metric(y_true, y_pred):
    batch = tf.shape(y_pred)[0]
    y_pred = tf.reshape(y_pred, (batch, -1, 3))
    y_true = tf.reshape(y_true, (batch, -1, 3))
    return tf.sqrt(tf.reduce_mean(tf.square(y_pred - y_true)))/1.5

# -----------------------------------------
# MAE
# -----------------------------------------
def mae_metric(y_true, y_pred):
    return tf.reduce_mean(tf.abs(y_pred - y_true))/1.5

# -----------------------------------------
# RMSE
# -----------------------------------------
def rmse_metric(y_true, y_pred):
    return tf.sqrt(tf.reduce_mean(tf.square(y_pred - y_true)))/1.5

# -------------------------
# CBAM Attention (Channel + Spatial)
# -------------------------
def cbam_block(x, reduction=8):
    channels = x.shape[-1]

    # ----- Channel Attention -----
    avg_pool = layers.GlobalAveragePooling1D()(x)
    max_pool = layers.GlobalMaxPooling1D()(x)

    mlp = layers.Dense(channels // reduction, activation="swish")
    mlp_out = layers.Dense(channels)

    avg_out = mlp_out(mlp(avg_pool))
    max_out = mlp_out(mlp(max_pool))

    channel_attention = layers.Activation("sigmoid")(avg_out + max_out)
    channel_attention = layers.Reshape((1, channels))(channel_attention)
    x = layers.Multiply()([x, channel_attention])

    # ----- Spatial Attention -----
    avg_pool = keras.ops.mean(x, axis=-1, keepdims=True)
    max_pool = keras.ops.max(x, axis=-1, keepdims=True)
    concat = layers.Concatenate(axis=-1)([avg_pool, max_pool])

    spatial_attention = layers.Conv1D(1, kernel_size=7, padding="same",
                                      activation="sigmoid")(concat)
    x = layers.Multiply()([x, spatial_attention])

    return x

# -------------------------
# Residual CNN Block
# -------------------------
def residual_cnn_block(x, filters):
    shortcut = x

    x = layers.Conv1D(filters, 5, padding="same", activation="swish")(x)
    x = layers.Conv1D(filters, 5, padding="same", activation="swish")(x)

    if shortcut.shape[-1] != filters:
        shortcut = layers.Conv1D(filters, 1, padding="same")(shortcut)

    return layers.Add()([x, shortcut])

# -------------------------
# Build Model
# -------------------------
def build_residual_cnn_cbam_small(input_dim, output_dim=12):
    inputs = layers.Input(shape=(input_dim,))
    x = layers.Reshape((input_dim, 1))(inputs)

    # CNN Block 1
    x = residual_cnn_block(x, 64)
    x = cbam_block(x)
    x = layers.MaxPooling1D(2)(x)

    # CNN Block 2
    x = residual_cnn_block(x, 128)
    x = cbam_block(x)

    # Decoder
    x = layers.Flatten()(x)
    x = layers.Dense(256, activation="swish")(x)
    x = layers.Dense(128, activation="swish")(x)

    # IMPORTANT: output normalized to (-1, 1)
    outputs = layers.Dense(output_dim, activation="linear")(x)

    model = Model(inputs, outputs)

    # Compile with Kabsch CRMSD as loss
    model.compile(
        optimizer=keras.optimizers.Adam(1e-4),
        loss=kabsch_crmsd,
        metrics=[kabsch_crmsd, rmsd_metric, mae_metric, rmse_metric]
    )

    return model

model = build_residual_cnn_cbam_small(
    input_dim=x_train.shape[1],
    output_dim=12
)

# Train WITHOUT validation
history = model.fit(
    x_train, y_train,
    epochs=100,
    batch_size=128,
    verbose=1
)

# Evaluate on TEST set
test_results = model.evaluate(x_test, y_test, verbose=1)
print("Test results:", test_results)

import numpy as np

scale = (y_scaler.data_max_ - y_scaler.data_min_) / 2
mean_scale = np.mean(scale)   # average scale across all 12 coordinates

best_norm_crmsd = 3.2882e-04
best_real_crmsd = best_norm_crmsd * mean_scale
print("Final CRMSD (Å):", best_real_crmsd)

import numpy as np
import matplotlib.pyplot as plt

# 1. Predict normalized output
y_pred_norm = model.predict(x_train)

# 2. Limit to first 200 samples
y_pred_200 = y_pred_norm[:200]
y_train_200 = y_train[:200]

# 3. Compute per-target offsets
offsets = np.mean(y_train_200, axis=0) - np.mean(y_pred_200, axis=0)

# 4. Apply the shift
y_pred_shifted = y_pred_200 + offsets

# 5. Plot
target_columns = ["CAx", "CAy", "CAz",
                  "Nx", "Ny", "Nz",
                  "Cx", "Cy", "Cz",
                  "Ox", "Oy", "Oz"]

plt.figure(figsize=(18, 20))

for i in range(12):
    plt.subplot(4, 3, i + 1)
    plt.plot(y_train_200[:, i], label="Actual (normalized)", alpha=0.8)
    plt.plot(y_pred_shifted[:, i], label="Predicted + offset", alpha=0.8)
    plt.title(target_columns[i])
    plt.xlabel("Sample Index")
    plt.ylabel("Normalized Value")
    plt.legend()

plt.tight_layout()
plt.show()